version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: C:\projects\core
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: >-
    mkdir c:\projects\core\build

    cd c:\projects\core\build

    cmake -G "Visual Studio 15 2017" ..

    cmake --build . --target ALL_BUILD --config Release
test_script:
- cmd: >-
    cd c:\projects\core\build

    ctest
deploy: off